[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hanged-man"
version = "1.0.0"
description = "A simple console game that is known as hangedman"
authors = [ 
    {name = "Sofie Brouwers", email = "sisbrouwers@tudelft.nl"},
]